name: My fisrt Workflow

on:
 push:
 pull_request:
 workflow_dispatch:
 
jobs:
    myfirstjob:
              name: First Job
              runs-on: ubuntu-latest
              steps:
              - name: step one
                uses: actions/checkout@v3
              - name: step two
                run: |
                  touch ${{ secrets.MY_FISRT_SECRET }}.yaml
                  echo "this is Luis Carranza" >> ${{ secrets.MY_FISRT_SECRET }}.yaml
                  cat ${{ secrets.MY_FISRT_SECRET }}.yaml
                  pwd
    mysecondjob:
               needs: [myfirstjob]
               name: Second Job
               runs-on: macos-latest
               steps:
               - name: step one
                 run: date
    mythirdjob:
               name: thrid Job
               runs-on: windows-latest
               steps:
               - name: step one
                 run: date
